# ============================================================================
# STANDALONE POSTGRESQL WITH PGVECTOR
# ============================================================================
# Deploy PostgreSQL in a separate Docker container
# Usage: docker-compose -f docker-postgres-standalone.yml up -d
# ============================================================================

version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: flask_llm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-homework_db}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-postgres.sh:/docker-entrypoint-initdb.d/01-init.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-homework_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - flask_network

volumes:
  postgres_data:
    driver: local

networks:
  flask_network:
    driver: bridge
